name: my_tome
<<<<<<< HEAD
<<<<<<< HEAD
description: A Flutter app for managing personal book collection.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.2
=======
description: A new Flutter project integrated with Firebase.
publish_to: 'none'

version: 1.0.0+1
=======
description: A lightweight reader app with local caching and Firebase sync.
version: 0.1.0
publish_to: 'none'
>>>>>>> 652928c0213b4284ebf349589dd4187ac5674b9b

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.16.0
>>>>>>> c7d6be6a991323bdcd66709b7c0ff3ed573369b5
=======
  cloud_firestore: ^5.4.2
  firebase_core: ^3.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
>>>>>>> 652928c0213b4284ebf349589dd4187ac5674b9b

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
<<<<<<< HEAD
  flutter_lints: ^2.0.0
=======
  flutter_lints: ^3.0.1
>>>>>>> c7d6be6a991323bdcd66709b7c0ff3ed573369b5
=======
  flutter_lints: ^4.0.0
>>>>>>> 652928c0213b4284ebf349589dd4187ac5674b9b

flutter:
  uses-material-design: true
